#!/bin/bash

DEFAULT_GROUP_ID=$(basename $(pwd))
DEFAULT_ARTIFACT_ID=$DEFAULT_GROUP_ID
DEFAULT_PACKAGING=jar
DEFAULT_VERSION=1.0.0-SNAPSHOT
DEFAULT_NAME=$DEFAULT_ARTIFACT_ID
OUTPUT=$(readlink -f pom.xml)

echo -e "Create a new Maven POM by entering some basic information.\n"

read -p "Group Id: ($DEFAULT_GROUP_ID) " GROUP_ID
GROUP_ID=${GROUP_ID:-$DEFAULT_GROUP_ID}

read -p "Artifact Id: ($DEFAULT_ARTIFACT_ID) " ARTIFACT_ID
ARTIFACT_ID=${ARTIFACT_ID:-$DEFAULT_ARTIFACT_ID}

read -p "Packaging: ($DEFAULT_PACKAGING) " PACKAGING
PACKAGING=${PACKAGING:-$DEFAULT_PACKAGING}

read -p "Version: ($DEFAULT_VERSION) " VERSION
VERSION=${VERSION:-$DEFAULT_VERSION}

read -p "Name: ($DEFAULT_NAME) " NAME
NAME=${NAME:-$DEFAULT_NAME}

read -p "Description: " DESCRIPTION

read -r -d '' POM <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>$GROUP_ID</groupId>
	<artifactId>$ARTIFACT_ID</artifactId>
	<packaging>$PACKAGING</packaging>
	<version>$VERSION</version>
	
	<name>$NAME</name>
	<description>$DESCRIPTION</description>

</project>
EOF
echo -e "\n$POM\n"

read -p "Write to $OUTPUT? (yes) " OK

if [ ${OK:-yes} != 'yes' ]
then
	echo "Aborted."
	exit 1
fi

echo "$POM" > $OUTPUT
